### ISSUE TITLE
Move org-variable-pitch.el to its own MELPA repo

### ISSUE THREAD

**Issue by naclander** [cadadr/elisp#31]
Great work on org-variable-pitch.el. It would be really great if this was available on MELPA so that I don't have to download the source manually. Can you consider adding it to MELPA?

**Comment by cadadr** [comment]
Thanks, glad you like it!  I'll send Melpa a PR next weekend, after my
exams, and update this issue accordingly.

**Comment by cadadr** [comment]
Hi @naclander , I've submitted a pull request to melpa for this, you can follow it here: <https://github.com/melpa/melpa/pull/5417>.  I'll close this issue now, and repoen if the package is refused for any reason.

**Comment by naclander** [comment]
@cadadr I have a feeling submitting your entire elisp project will not be accepted. You mentioned you are not inclined to move org-variable-pitch into its own project, why is that?

**Comment by cadadr** [comment]
I'm not submitting the entire repo.  I use the :files directive to select only the relevant file(s) for each package (in this case only org-variable-pitch.el).  Maintaining all my packages in one repo has certain advantages for me, but Melpa maintainers don't like it because they use vcs tags for melpa-stable instead of the version header in the package itself, and want me to change the way I do things.  I do put up with that because I don't want to cause inconveniences to people who want to use my packages, even though I don't use package.el myself.  That said I do understand why they don't like the way I handle this and I wanted to tell them if they explicitly forbid that, I'm okay with finding an alternative (either split my repo up but more preferably just start a public ELPA archive myself, which seems to be rather easy to do), but if they don't, they I'm content with my method and want to keep doing the things the way I prefer.

**Comment by cadadr** [comment]
The PR for inclusion in Melpa has been accepted, closing.
