### ISSUE TITLE
forecast.el: how to correctly display rain symbols

### ISSUE THREAD

**Issue by inglada** [cadadr/elisp#45]
Hi,
Thanks for this nice package. I have installed the Quivira font in order to display the different symbols. I works for the moon, but not for the rain symbols (the precipitation probability). I did not find a face to customize for these symbols, as it is the case for the moon phases.
I guess that the org faces are used, but since I don't use Quivira for org, I don't see how to configure this.
Any idea?
Thanks!

**Comment by cadadr** [comment]
You're welcome!  Quivira is only used in the moon phase view next to the daylight bar.  The rest of the interface uses your default font (Quivira wouldn't work because it is a proportional-only font and it'd break the alignment of the UI).  Org faces are only used for the section headings, the rest, except the moon phase, does not have any face assigned.

I think your font does not include the necessary characters (unicode `#x2744`, `SNOWFLAKE`; and `#x26c6`, `RAIN`) that forecast.el uses.  You can switch to a font like DejaVu Sans Mono that has them, or modify `forecast-rain-symbol` and `forecast-snow-symbol` to some string value that your preferred font can display.  The Sun position char is hard coded, for which I'll soon push a fix.  You can have a look at `defcustom`s in the source code or `M-x customize-group RET forecast RET` to see all the possible customisations together with docs on their use.

If you want a face assigned to those characters (i.e. you don't want to change your font nor change the characters themselves), tell me, that's OK with me.  If you can't write the patch, I can do it in the coming days (all it takes would probably be a couple calls to `propertize` in `forecast--insert-upcoming-graph`).

**Comment by cadadr** [comment]
Update: 31aa493 added `forecast-sun-symbol` defcustom.

**Comment by cadadr** [comment]
I'm closing this issue for the lack of a follow up.

**Comment by inglada** [comment]
Hi, sorry for the lack of response.
I updated the package yesterday (from MELPA) and after trying what you suggested, I think that the bet would be to have a face for those characters. I am not able to write such a patch in elisp. If you do it, I would be happy to test.
Thanks.

**Comment by cadadr** [comment]
OK, I'll try to do that soon-ish, reopening the issue.

**Comment by cadadr** [comment]
Hi, sorry for the long time it took for me to get back to this (life issues).

I just pushed a commit (5f3e674) that adds `forecast-rain-symbol-face` that applies to `forecast-rain-symbol` and `forecast-snow-symbol-face` that applies to `forecast-snow-symbol`).  The commit is on devel, so not on MELPA yet.

I'll close the issue for now, if you need further help, don't hesitate to ask again.
