### ISSUE TITLE
org-variable-pitch.el: control over monospace initial whitespace 

### ISSUE THREAD

**Issue by mooseyboots** [cadadr/elisp#57]
hi @cadadr and thx for this great package.

i mainly use emacs/org for prose/poetry and it's really helpful for that kind of set up.

my question is: is it possible to disable initial spaces being monospace in particular contexts, specifically in org-verse blocks?

when using OVP, initial spaces are monospace everywhere, but the idea of using org-verse blocks is for any manual spacing/indentation to be preserved on export. when i export to odt, any spaces inserted before the first letter of a line are converted from monospace to non-monospace spaces, which significantly reduces the level of indentation. or would it be possible to avoid this, or is my only option to disable OVP in the whole file?

disabling OVP as a whole for org-verse blocks would also not work -- as then my block would be in a fixed pitch font, which would again mean the level of indentation was modified on export to odt (and to a non-monospace font).

**Comment by cadadr** [comment]
You're very welcome, I'm glad that it's useful to you.

This is an interesting question and I doubt I have a good answer for it. Sadly, I don't have time to look deeper in this issue for the time being, but if you're ever able to fix it for yourself, a PR is most welcome. Sorry for not being able to help.

My own solution is to use example blocks for verse, so that indentation is consistent in Org and in PDF exports. That of course might not be an option for you and also it seems to not work in ODT exports (to it may be tunable).

**Comment by cadadr** [comment]
OVP no longer maintained, cf. b28a70665b8db82323b57c2ee2f6e019cb9b92d3
